use anyhow::{Context, Result};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use chrono::Utc;
use jsonwebtoken::{decode, encode, Algorithm, DecodingKey, EncodingKey, Header, Validation};
use p256::ecdsa::SigningKey;
use pkcs8::{DecodePrivateKey, EncodePrivateKey, EncodePublicKey, LineEnding};
use serde::{Deserialize, Serialize};
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use crate::types::Role;

// ---------------------------------------------------------------------------
// Claims
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JwtClaims {
    pub sub: String,
    pub role: String,
    pub account: Option<String>,
    pub iss: String,
    pub aud: Vec<String>,
    pub exp: u64,
    pub iat: u64,
}

// ---------------------------------------------------------------------------
// Key bundle
// ---------------------------------------------------------------------------

pub struct JwtKeys {
    pub encoding_key: EncodingKey,
    pub decoding_key: DecodingKey,
    pub public_jwk: serde_json::Value,
}

// ---------------------------------------------------------------------------
// Load or generate
// ---------------------------------------------------------------------------

pub fn load_or_generate(key_path: &Path) -> Result<JwtKeys> {
    let pem = if key_path.exists() {
        std::fs::read_to_string(key_path)
            .with_context(|| format!("Reading JWT signing key: {}", key_path.display()))?
    } else {
        generate_and_save(key_path)?
    };

    keys_from_pem(&pem)
}

fn generate_and_save(key_path: &Path) -> Result<String> {
    let signing_key = SigningKey::random(&mut rand::rngs::OsRng);
    let pem = signing_key
        .to_pkcs8_pem(LineEnding::LF)
        .context("Serializing JWT signing key to PKCS8 PEM")?;

    if let Some(parent) = key_path.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    std::fs::write(key_path, pem.as_bytes())
        .with_context(|| format!("Writing JWT signing key: {}", key_path.display()))?;
    std::fs::set_permissions(key_path, std::fs::Permissions::from_mode(0o600))
        .with_context(|| format!("Setting permissions on JWT signing key: {}", key_path.display()))?;

    tracing::info!(path = %key_path.display(), "Generated new JWT signing key");
    Ok(pem.to_string())
}

fn keys_from_pem(pem: &str) -> Result<JwtKeys> {
    // Accept both PKCS#8 (BEGIN PRIVATE KEY, generated by shepherd-rs) and
    // SEC1 (BEGIN EC PRIVATE KEY, generated by the TypeScript shepherd).
    // jsonwebtoken/ring only accepts PKCS#8, so normalize to that first.
    let secret_key = p256::SecretKey::from_pkcs8_pem(pem)
        .or_else(|_| p256::SecretKey::from_sec1_pem(pem))
        .context("Parsing JWT signing key")?;
    let pkcs8_pem = secret_key
        .to_pkcs8_pem(LineEnding::LF)
        .context("Re-encoding JWT signing key as PKCS8")?;

    let encoding_key = EncodingKey::from_ec_pem(pkcs8_pem.as_bytes())
        .context("Loading JWT encoding key from PEM")?;

    let signing_key = SigningKey::from(&secret_key);
    let verifying_key = signing_key.verifying_key();

    let public_pem = verifying_key
        .to_public_key_pem(LineEnding::LF)
        .context("Serializing JWT public key")?;
    let decoding_key = DecodingKey::from_ec_pem(public_pem.as_bytes())
        .context("Loading JWT decoding key from PEM")?;

    let public_jwk = build_jwk(verifying_key);

    Ok(JwtKeys { encoding_key, decoding_key, public_jwk })
}

fn build_jwk(verifying_key: &p256::ecdsa::VerifyingKey) -> serde_json::Value {
    let point = verifying_key.to_encoded_point(false);
    let x = URL_SAFE_NO_PAD.encode(point.x().expect("P-256 x coordinate"));
    let y = URL_SAFE_NO_PAD.encode(point.y().expect("P-256 y coordinate"));
    serde_json::json!({
        "kty": "EC",
        "crv": "P-256",
        "x": x,
        "y": y,
        "use": "sig",
        "alg": "ES256",
    })
}

// ---------------------------------------------------------------------------
// Sign / verify
// ---------------------------------------------------------------------------

pub fn sign_jwt(
    keys: &JwtKeys,
    identity_uri: &str,
    role: &Role,
    account_name: Option<&str>,
) -> Result<String> {
    let now = Utc::now().timestamp() as u64;
    let claims = JwtClaims {
        sub: identity_uri.to_string(),
        role: format!("{:?}", role).to_lowercase(),
        account: account_name.map(str::to_string),
        iss: "shepherd".to_string(),
        aud: vec!["shepherd".to_string()],
        exp: now + 3600,
        iat: now,
    };
    encode(&Header::new(Algorithm::ES256), &claims, &keys.encoding_key)
        .context("Signing JWT")
}

pub fn verify_jwt(keys: &JwtKeys, token: &str) -> Result<JwtClaims> {
    let mut validation = Validation::new(Algorithm::ES256);
    validation.set_issuer(&["shepherd"]);
    validation.set_audience(&["shepherd"]);

    let data = decode::<JwtClaims>(token, &keys.decoding_key, &validation)
        .context("Verifying JWT")?;
    Ok(data.claims)
}

pub fn jwks_response(keys: &JwtKeys) -> serde_json::Value {
    serde_json::json!({ "keys": [keys.public_jwk] })
}
